[workspace]
resolver = "2"

members = [
    "apps/cli",
    "apps/gui/src-tauri",
    "crates/factorio",
    "crates/downloader",
    "crates/parser",
]

[workspace.package]
version = "0.3.3"
authors = ["Vaibhav Vikas <vaibhavvikas@users.noreply.github.com>"]
license = "MIT"
repository = "https://github.com/vaibhavvikas/factorio-mod-downloader"
edition = "2024"
